---
title: "An analysis of the COVID-19 pandemic in Bangladesh"
author: "Dilinie Seimon"
date: '2020-09-16'
categories: []
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-09-16T21:22:35+10:00'
projects: []
slug: an-analysis-of-covid-19-pandemic-in-bangladesh
subtitle: ''
summary: ''
tags: []
authors: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(readr)
library(tidyverse)
```

```{r reading-in-data}
tidycovid19_bangla <- read_csv(here::here("content/post/covid-19-bangladesh/data/tidycovid19-bangladesh-data.csv"))
```

## The spread of COVID-19

```{r trend-plot}
options(scipen = 999)
tidycovid19_bangla %>%
  select(date, confirmed, deaths, recovered) %>%
  pivot_longer(cols = -date,
               names_to = "Type",
               values_to = "Cases") %>%
  ggplot(aes(x = date,
             y = Cases,
             color = Type)) +
  geom_line(size=1.3) +
  theme_light() +
  labs(x = "Date")+ 
  scale_x_date(date_breaks = "months" , date_labels = "%b-%y")
```

## Measures in response to COVID-19